pub const GENERATED_TYPESCRIPT: &str = r#"// Generated by mission-protocol-export. Do not edit by hand.
export type Branded<T, B extends string> = T & { readonly __brand: B };
export type MissionId = Branded<string, "MissionId">;
export type RouteId = Branded<string, "RouteId">;
export type EventId = Branded<string, "EventId">;
export type Rfc3339 = Branded<string, "Rfc3339">;

export type IpcCommand =
  | "Handshake"
  | "CreateMission"
  | "UpdateMissionContract"
  | "LaunchRoute"
  | "RequestSafePause"
  | "ForceTerminate"
  | "ResolveApproval"
  | "SubscribeMission"
  | "BuildRecoveryPackage";

export type Actor = "user" | "renderer" | "supervisor" | "agent";

export interface RequestEnvelope {
  requestId: string;
  expectedRevision?: number;
  actor: Actor;
  command: IpcCommand;
}

export interface OkResponse<T> {
  requestId: string;
  revision: number;
  value: T;
}

export interface ErrorResponse {
  requestId: string;
  code: string;
  messageKey: string;
  retryable: boolean;
  details?: unknown;
}

export interface MissionReadModel {
  missionId: string;
  revision: number;
  routeState: string;
  evidenceVerified: number;
  evidenceRequired: number;
  incomplete: boolean;
}

export interface MissionEventSummary {
  eventId: string;
  sequence: number;
  kind: string;
  occurredAt: Rfc3339;
}

export const IPC_COMMANDS: readonly IpcCommand[] = [
  "Handshake",
  "CreateMission",
  "UpdateMissionContract",
  "LaunchRoute",
  "RequestSafePause",
  "ForceTerminate",
  "ResolveApproval",
  "SubscribeMission",
  "BuildRecoveryPackage",
] as const;

"#;

pub fn typescript_bindings() -> &'static str {
    GENERATED_TYPESCRIPT
}
