pub const GENERATED_TYPESCRIPT: &str = r#"// Generated by mission-protocol-export. Do not edit by hand.
export type Branded<T, B extends string> = T & { readonly __brand: B };
export type MissionId = Branded<string, "MissionId">;
export type RouteId = Branded<string, "RouteId">;
export type EventId = Branded<string, "EventId">;
export type Rfc3339 = Branded<string, "Rfc3339">;

export type ProviderId = "codex" | "claude" | "opencode" | "zcode";

export interface ProviderCapability {
  provider: ProviderId;
  agent: string;
  version?: string;
  installState: "installed" | "missing" | "detected_not_runnable" | "unknown";
  available: boolean;
  unavailableReason?: string;
  structuredEvents: boolean;
  resume: boolean;
  approval: boolean;
  safePause: boolean;
  terminalFallback: boolean;
}

export interface LoadoutSnapshot {
  provider: ProviderId;
  model?: string;
  configFingerprint: string;
  hooksFingerprint: string;
  skillsFingerprint: string;
  pluginsFingerprint: string;
  mcpFingerprint: string;
}

export interface StartAgentRequest {
  missionId: MissionId;
  routeId: RouteId;
  provider?: ProviderId;
  projectRoot: string;
  routeWorkspace: string;
  readOnly: boolean;
  approvedEnvironment: Array<[string, string]>;
  model?: string;
  goal?: string;
  loadoutFingerprint: string;
  resumeThreadId?: string;
  loadout?: LoadoutSnapshot;
}

export type IpcCommand =
  | "Handshake"
  | "CreateMission"
  | "UpdateMissionContract"
  | "LaunchRoute"
  | "RequestSafePause"
  | "ForceTerminate"
  | "ResolveApproval"
  | "SubscribeMission"
  | "ReviewMemory"
  | "BuildContextPack"
  | "BuildRecoveryPackage"
  | "VerifyRecovery"
  | "ResolveRecovery"
  | "HandoffProvider";

export type ContinuityErrorCode =
  | "PROVIDER_UNAVAILABLE"
  | "PROVIDER_NOT_SELECTED"
  | "LOADOUT_MISMATCH"
  | "MEMORY_SOURCE_REQUIRED"
  | "CONTEXTPACK_BUDGET_EXCEEDED"
  | "RECOVERY_TAMPERED"
  | "RECOVERY_SEQUENCE_INVALID"
  | "RECOVERY_PACKAGE_REQUIRED"
  | "RECOVERY_PACKAGE_INVALID"
  | "RECOVERY_NOT_REQUIRED"
  | "RECOVERY_DECISION_REQUIRED"
  | "RECOVERY_VERIFY_FAILED"
  | "RECOVERY_RESOLUTION_FAILED"
  | "PENDING_APPROVAL_MISMATCH"
  | "PERMISSION_EXPANSION"
  | "UNSUPPORTED_COMMAND";

export interface ReviewMemoryRequest {
  missionId: MissionId;
  candidateIds: string[];
  expectedRevision: number;
}

export interface ContextPackRequest {
  missionId: MissionId;
  routeId: RouteId;
  maxTokens: number;
  expectedSequence: number;
}

export interface BuildRecoveryPackageRequest {
  missionId: MissionId;
  routeId: RouteId;
  contractVersion: number;
  checkpointId: string;
  ledgerSequence: number;
  loadoutFingerprint: string;
  contextPackHash: string;
  pendingApprovalHash?: string;
}

export interface ProviderHandoffRequest {
  missionId: MissionId;
  routeId: RouteId;
  targetProvider: ProviderId;
  contextPackHash: string;
  pendingApprovalHash?: string;
}

export type Actor = "user" | "renderer" | "supervisor" | "agent";

export type ApprovalDecision = "approve" | "deny" | "revoke";
export type ApprovalGrantScope = "once" | "route_action_class";

export interface ResolveApproval {
  approvalId: string;
  expectedRevision: number;
  decision: ApprovalDecision;
  missionId: string;
  routeId: string;
  contractVersion: number;
  loadoutFingerprint: string;
  actionDigest: string;
  nowMs: number;
  scope?: ApprovalGrantScope;
}

export interface RequestEnvelope {
  requestId: string;
  expectedRevision?: number;
  actor: Actor;
  command: IpcCommand;
}

export interface OkResponse<T> {
  requestId: string;
  revision: number;
  value: T;
}

export interface ErrorResponse {
  requestId: string;
  code: string;
  messageKey: string;
  retryable: boolean;
  details?: unknown;
}

export interface MissionReadModel {
  missionId: string;
  revision: number;
  routeState: string;
  evidenceVerified: number;
  evidenceRequired: number;
  incomplete: boolean;
}

export interface MissionEventSummary {
  eventId: string;
  sequence: number;
  kind: string;
  occurredAt: Rfc3339;
}

export const IPC_COMMANDS: readonly IpcCommand[] = [
  "Handshake",
  "CreateMission",
  "UpdateMissionContract",
  "LaunchRoute",
  "RequestSafePause",
  "ForceTerminate",
  "ResolveApproval",
  "SubscribeMission",
  "ReviewMemory",
  "BuildContextPack",
  "BuildRecoveryPackage",
  "VerifyRecovery",
  "ResolveRecovery",
  "HandoffProvider",
] as const;

"#;

pub fn typescript_bindings() -> &'static str {
    GENERATED_TYPESCRIPT
}
